### ISSUE TITLE
Test suite fails (cannot import name pystone)

### ISSUE THREAD

**Issue by nidico** [zopefoundation/zope.testbrowser#5]
Building zope.testbrowser on my Fedora 18 machine with python-2.7.3 and virtualenv-1.9.1 from PyPI fails, using the enclosed buildout. This came up in #4 originally. This is the full stack trace:

```
nico@pesto $ bin/test
Running zope.testrunner.layer.UnitTests tests:
  Set up zope.testrunner.layer.UnitTests in 0.000 seconds.


Failure in test /home/nico/src/zope.testbrowser/src/zope/testbrowser/README.txt
Failed doctest test for README.txt
  File "/home/nico/src/zope.testbrowser/src/zope/testbrowser/README.txt", line 0

----------------------------------------------------------------------
File "/home/nico/src/zope.testbrowser/src/zope/testbrowser/README.txt", line 119, in README.txt
Failed example:
    verifyObject(interfaces.IBrowser, browser)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib64/python2.7/doctest.py", line 1289, in __run
        compileflags, 1) in test.globs
      File "<doctest README.txt[20]>", line 1, in <module>
        verifyObject(interfaces.IBrowser, browser)
      File "/home/nico/src/zope.testbrowser/eggs/zope.interface-4.0.5-py2.7-linux-x86_64.egg/zope/interface/verify.py", line 105, in verifyObject
        return _verify(iface, candidate, tentative, vtype='o')
      File "/home/nico/src/zope.testbrowser/eggs/zope.interface-4.0.5-py2.7-linux-x86_64.egg/zope/interface/verify.py", line 55, in _verify
        attr = getattr(candidate, name)
      File "/home/nico/src/zope.testbrowser/src/zope/testbrowser/browser.py", line 299, in lastRequestPystones
        return self.timer.elapsedPystones
      File "/home/nico/src/zope.testbrowser/src/zope/testbrowser/browser.py", line 176, in elapsedPystones
        return self.elapsedSeconds * self.pystonesPerSecond
      File "/home/nico/src/zope.testbrowser/src/zope/testbrowser/browser.py", line 135, in pystonesPerSecond
        from test import pystone
    ImportError: cannot import name pystone
----------------------------------------------------------------------
File "/home/nico/src/zope.testbrowser/src/zope/testbrowser/README.txt", line 1380, in README.txt
Failed example:
    browser.lastRequestPystones < 10000 # really big number for safety
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib64/python2.7/doctest.py", line 1289, in __run
        compileflags, 1) in test.globs
      File "<doctest README.txt[388]>", line 1, in <module>
        browser.lastRequestPystones < 10000 # really big number for safety
      File "/home/nico/src/zope.testbrowser/src/zope/testbrowser/browser.py", line 299, in lastRequestPystones
        return self.timer.elapsedPystones
      File "/home/nico/src/zope.testbrowser/src/zope/testbrowser/browser.py", line 176, in elapsedPystones
        return self.elapsedSeconds * self.pystonesPerSecond
      File "/home/nico/src/zope.testbrowser/src/zope/testbrowser/browser.py", line 135, in pystonesPerSecond
        from test import pystone
    ImportError: cannot import name pystone

  Ran 19 tests with 1 failures and 0 errors in 0.375 seconds.
Tearing down left over layers:
  Tear down zope.testrunner.layer.UnitTests in 0.000 seconds.
```

**Comment by bazz2** [comment]
ImportError: cannot import name pystone -> solution is yum install python-test.
Thank you, it works~~

**Comment by ramadivyasri** [comment]
I'm facing the same issue:
File "/usr/lib/python2.7/site-packages/dpkt/decorators.py", line 4, in <module>
    from test import pystone
ImportError: cannot import name pystone

But, yum install python-test did not resolve the issue. What else can be done?
