### ISSUE TITLE
Careless use of CSS selectors breaks with new BeautifulSoup

### ISSUE THREAD

**Issue by mgedmin** [zopefoundation/zope.testbrowser#61]
zope.testbrowser relies on BeautifulSoup's implementation of CSS selectors to query HTML nodes.  The latest release of BeautifulSoup requires CSS selectors to follow the CSS spec in ways where previously it allowed lax values.  Since zope.testbrowser doesn't actually follow the CSS spec (inadequate quoting), this causes problems like https://github.com/zopefoundation/zc.catalog/issues/8.

One instance (from the above bug) is this line in getControlLabels():

```
        forlbls = html.select('label[for=%s]' % controlid)
```

The %s should apparently be quoted with double quotes in case `controlid` is not a valid CSS identifier.

Other instances of this may lurk.  https://facelessuser.github.io/soupsieve/#beautiful-soup-differences has a list of things we should watch for.

**Comment by mgedmin** [comment]
Stumbled upon another instance of this:

```
Failed example:
    browser.getLink(id='form.q_3.2_delete').click()
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest self-review-2014.txt[146]>", line 1, in <module>
        browser.getLink(id='form.q_3.2_delete').click()
      File "/home/mg/src/zopefoundation/zope.testbrowser/src/zope/testbrowser/browser.py", line 319, in getLink
        links = html.select(qa)
      File "/home/mg/src/ivija/.tox/py27-latest/local/lib/python2.7/site-packages/bs4/element.py", line 1376, in select
        return soupsieve.select(selector, self, namespaces, limit, **kwargs)
      File "/home/mg/src/ivija/.tox/py27-latest/local/lib/python2.7/site-packages/soupsieve/__init__.py", line 114, in select
        return compile(select, namespaces, flags, **kwargs).select(tag, limit)
      File "/home/mg/src/ivija/.tox/py27-latest/local/lib/python2.7/site-packages/soupsieve/__init__.py", line 63, in compile
        return cp._cached_css_compile(pattern, namespaces, custom, flags)
      File "/home/mg/src/ivija/.tox/py27-latest/local/lib/python2.7/site-packages/backports/functools_lru_cache.py", line 137, in wrapper
        result = user_function(*args, **kwds)
      File "/home/mg/src/ivija/.tox/py27-latest/local/lib/python2.7/site-packages/soupsieve/css_parser.py", line 214, in _cached_css_compile
        CSSParser(pattern, custom=custom_selectors, flags=flags).process_selectors(),
      File "/home/mg/src/ivija/.tox/py27-latest/local/lib/python2.7/site-packages/soupsieve/css_parser.py", line 1113, in process_selectors
        return self.parse_selectors(self.selector_iter(self.pattern), index, flags)
      File "/home/mg/src/ivija/.tox/py27-latest/local/lib/python2.7/site-packages/soupsieve/css_parser.py", line 946, in parse_selectors
        key, m = next(iselector)
      File "/home/mg/src/ivija/.tox/py27-latest/local/lib/python2.7/site-packages/soupsieve/css_parser.py", line 1100, in selector_iter
        raise SelectorSyntaxError(msg, self.pattern, index)
    SelectorSyntaxError: Malformed class selector at position 10
      line 1:
    a#form.q_3.2_delete
```
